name: Make HACS Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Zip File
      run: |
        # Create release directory and copy integration files
        mkdir -p release/custom_components/windmillfan
        cp -r custom_components/windmillfan/* release/custom_components/windmillfan/
        cp README.md release/
        cp hacs.json release/
        
        # Create zip file
        cd release
        zip -r ../hacs_windmill.zip .
        cd ..

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: hacs_windmill.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}